name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Upgrade pip
      run: python -m pip install --upgrade pip
    - name: Install this package
      run: python -m pip install -e .[test]
    - name: Lint with ruff
      run: ruff .
    - name: Test with pytest
      run: pytest
